import "dotenv/config";
import bcrypt from "bcryptjs";
import { PrismaClient } from "@prisma/client";
import { createEmptyPage, createNode, insertNode } from "@pgcms/shared";
import { seedAdvancedHomepage } from "./seed-homepage.ts";
import { seedOurCharitiesPage } from "./seed-our-charities.ts";

const prisma = new PrismaClient();

const PLACEHOLDER = (label: string, size = "1200x630") =>
  `https://placehold.co/${size}/0b1220/ffffff?text=${encodeURIComponent(label)}`;

async function seedDemoCollections() {
  const newsCollection = await prisma.collection.upsert({
    where: { slug: "news" },
    update: {},
    create: { name: "News", slug: "news" },
  });
  const eventsCollection = await prisma.collection.upsert({
    where: { slug: "events" },
    update: {},
    create: { name: "Events", slug: "events" },
  });

  const now = new Date();

  function buildItemContent(title: string, subtitle: string) {
    let root = createEmptyPage();
    const hero = createNode("imageBackgroundSection");
    hero.props.heading = title;
    hero.props.subheading = subtitle;
    hero.style.backgroundImage = PLACEHOLDER(title, "1600x700");
    hero.style.minHeight = "420px";
    root = insertNode(root, root.id, hero);
    const body = createNode("richText");
    body.props.html =
      "<p>This is demo content generated by the seed script. Replace it using the page builder to publish your own articles, events, and resources.</p>" +
      "<h3>What you'll get</h3><ul><li>Reusable sections and blocks</li><li>Performance-friendly motion</li><li>SEO fields and OpenGraph images</li></ul>";
    root = insertNode(root, root.id, body);
    return root;
  }

  const newsItems = [
    {
      slug: "record-fundraising-year",
      title: "Federation Announces Record Fundraising Year",
      excerpt:
        "Member clubs raised more for our appeals in the last year than ever before.",
    },
    {
      slug: "education-grant-opens",
      title: "Education Grant Opens for New Applications",
      excerpt:
        "The Diamond Education Grant is now accepting applications for the next cohort.",
    },
    {
      slug: "emergency-fund-response",
      title: "Emergency Relief Fund Responds to Flooding",
      excerpt:
        "Rapid-response aid was distributed to affected communities within 72 hours.",
    },
  ];
  for (const item of newsItems) {
    await prisma.collectionItem.upsert({
      where: {
        collectionId_slug: { collectionId: newsCollection.id, slug: item.slug },
      },
      update: {
        title: item.title,
        excerpt: item.excerpt,
        coverImage: PLACEHOLDER(item.title, "1200x630"),
        content: buildItemContent(item.title, item.excerpt) as any,
        status: "PUBLISHED",
        publishedAt: now,
        seoTitle: item.title,
        seoDescription: item.excerpt,
        ogImage: PLACEHOLDER(item.title, "1200x630"),
      },
      create: {
        collectionId: newsCollection.id,
        slug: item.slug,
        title: item.title,
        excerpt: item.excerpt,
        coverImage: PLACEHOLDER(item.title, "1200x630"),
        content: buildItemContent(item.title, item.excerpt) as any,
        status: "PUBLISHED",
        publishedAt: now,
        seoTitle: item.title,
        seoDescription: item.excerpt,
        ogImage: PLACEHOLDER(item.title, "1200x630"),
      },
    });
  }

  const eventItems = [
    {
      slug: "global-convention-2026",
      title: "Global Convention 2026",
      excerpt: "Three days of workshops, speakers, and member-led sessions.",
    },
    {
      slug: "regional-leadership-summit",
      title: "Regional Leadership Summit",
      excerpt: "Skill-building sessions for club leaders and new members.",
    },
    {
      slug: "community-action-week",
      title: "Community Action Week",
      excerpt:
        "A coordinated week of grassroots projects across local clubs worldwide.",
    },
  ];
  for (const item of eventItems) {
    await prisma.collectionItem.upsert({
      where: {
        collectionId_slug: {
          collectionId: eventsCollection.id,
          slug: item.slug,
        },
      },
      update: {
        title: item.title,
        excerpt: item.excerpt,
        coverImage: PLACEHOLDER(item.title, "1200x630"),
        content: buildItemContent(item.title, item.excerpt) as any,
        status: "PUBLISHED",
        publishedAt: now,
        seoTitle: item.title,
        seoDescription: item.excerpt,
        ogImage: PLACEHOLDER(item.title, "1200x630"),
      },
      create: {
        collectionId: eventsCollection.id,
        slug: item.slug,
        title: item.title,
        excerpt: item.excerpt,
        coverImage: PLACEHOLDER(item.title, "1200x630"),
        content: buildItemContent(item.title, item.excerpt) as any,
        status: "PUBLISHED",
        publishedAt: now,
        seoTitle: item.title,
        seoDescription: item.excerpt,
        ogImage: PLACEHOLDER(item.title, "1200x630"),
      },
    });
  }
}

async function main() {
  const email = process.env.SEED_ADMIN_EMAIL ?? "admin@example.com";
  const password = process.env.SEED_ADMIN_PASSWORD ?? "ChangeMe123!";

  const existingAdmin = await prisma.user.findUnique({ where: { email } });
  if (!existingAdmin) {
    const passwordHash = await bcrypt.hash(password, 10);
    await prisma.user.create({ data: { email, passwordHash, role: "ADMIN" } });
    console.log(`Seeded admin user: ${email}`);
  } else {
    console.log(`Admin user already exists: ${email}`);
  }

  const themeCount = await prisma.siteTheme.count();
  if (themeCount === 0) {
    await prisma.siteTheme.create({
      data: {
        siteName: "Global Impact Alliance",
        primaryColor: "#f97316",
        secondaryColor: "#0b1220",
        backgroundColor: "#ffffff",
        textColor: "#111827",
        headingFont: "Poppins",
        bodyFont: "Inter",
        logoUrl: "https://placehold.co/180x48/ffffff/0b1220?text=Global+Impact",
        faviconUrl: "https://placehold.co/64x64/f97316/0b1220?text=G",
      },
    });
  }

  await seedDemoCollections();
  await seedAdvancedHomepage(prisma);
  await seedOurCharitiesPage(prisma);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
